import { Transaction, Budget, SavingsGoal, UserSettings } from '../types';

export const INITIAL_SETTINGS: UserSettings = {
  name: 'Ruks',
  email: 'ruks@example.com',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256&h=256',
  currency: '₹',
  theme: 'light',
  notifications: {
    budgetAlerts: true,
    paymentReminders: true,
    weeklySummary: true,
  },
};

export const INITIAL_SAVINGS_GOALS: SavingsGoal[] = [
  {
    id: 'goal-1',
    name: 'MacBook',
    currentAmount: 65000,
    targetAmount: 90000,
    targetDate: '2026-12-15',
    category: 'Electronics',
    icon: 'laptop',
    color: '#8b5cf6',
  },
  {
    id: 'goal-2',
    name: 'Emergency Fund',
    currentAmount: 35000,
    targetAmount: 50000,
    targetDate: '2027-06-30',
    category: 'Safety',
    icon: 'shield',
    color: '#0ea5e9',
  },
  {
    id: 'goal-3',
    name: 'Travel',
    currentAmount: 18500,
    targetAmount: 30000,
    targetDate: '2027-09-01',
    category: 'Vacation',
    icon: 'plane',
    color: '#14b8a6',
  },
];

export const INITIAL_BUDGETS: Budget[] = [
  { id: 'b-1', category: 'Food', amount: 8000, month: '2026-09' },
  { id: 'b-2', category: 'Shopping', amount: 5000, month: '2026-09' },
  { id: 'b-3', category: 'Transport', amount: 4000, month: '2026-09' },
  { id: 'b-4', category: 'Bills', amount: 6000, month: '2026-09' },
  { id: 'b-5', category: 'Entertainment', amount: 3000, month: '2026-09' },
  { id: 'b-6', category: 'Health', amount: 3000, month: '2026-09' },
  { id: 'b-7', category: 'Other', amount: 6000, month: '2026-09' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  // September 2026 - matches reference values
  {
    id: 'tx-1',
    type: 'expense',
    description: 'Swiggy',
    category: 'Food',
    amount: 420,
    date: '2026-09-07',
    notes: 'Dinner delivery with friends',
    merchant: 'Swiggy',
  },
  {
    id: 'tx-2',
    type: 'expense',
    description: 'Uber',
    category: 'Transport',
    amount: 180,
    date: '2026-09-06',
    notes: 'Ride to city center',
    merchant: 'Uber',
  },
  {
    id: 'tx-3',
    type: 'expense',
    description: 'Amazon',
    category: 'Shopping',
    amount: 1299,
    date: '2026-09-05',
    notes: 'Wireless ergonomic mouse and desk mat',
    merchant: 'Amazon',
  },
  {
    id: 'tx-4',
    type: 'expense',
    description: 'Electricity Bill',
    category: 'Bills',
    amount: 1850,
    date: '2026-09-04',
    notes: 'BESCOM August utilities',
    merchant: 'Electricity Board',
  },
  {
    id: 'tx-5',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 50000,
    date: '2026-09-01',
    notes: 'Monthly company payroll credit',
    merchant: 'TechCorp Pvt Ltd',
  },
  {
    id: 'tx-6',
    type: 'expense',
    description: 'Fresh Groceries',
    category: 'Food',
    amount: 2000,
    date: '2026-09-03',
    notes: 'Weekly staples and vegetables',
    merchant: 'Nature Basket',
  },
  {
    id: 'tx-7',
    type: 'expense',
    description: 'Zara Apparel',
    category: 'Shopping',
    amount: 2901,
    date: '2026-09-11',
    notes: 'Autumn casual shirts',
    merchant: 'Zara',
  },
  {
    id: 'tx-8',
    type: 'expense',
    description: 'Metro Pass & Fuel',
    category: 'Transport',
    amount: 2670,
    date: '2026-09-10',
    notes: 'Monthly smart transit recharge & fuel',
    merchant: 'Metro Rail',
  },
  {
    id: 'tx-9',
    type: 'expense',
    description: 'WiFi & Mobile postpaid',
    category: 'Bills',
    amount: 2350,
    date: '2026-09-02',
    notes: 'Airtel Fiber Gigabit connection',
    merchant: 'Airtel',
  },
  {
    id: 'tx-10',
    type: 'expense',
    description: 'Cinema & Streaming',
    category: 'Entertainment',
    amount: 1900,
    date: '2026-09-18',
    notes: 'IMAX movie tickets & subscriptions',
    merchant: 'PVR Cinemas',
  },
  {
    id: 'tx-11',
    type: 'expense',
    description: 'Pharmacy & Vitamins',
    category: 'Health',
    amount: 1650,
    date: '2026-09-19',
    notes: 'Daily vitamins and eye drops',
    merchant: 'Apollo Pharmacy',
  },
  {
    id: 'tx-12',
    type: 'expense',
    description: 'Bookstore & Stationary',
    category: 'Other',
    amount: 600,
    date: '2026-09-24',
    notes: 'Finance journal and gel pens',
    merchant: 'Crossword',
  },
  {
    id: 'tx-13',
    type: 'expense',
    description: 'Dry Cleaning Service',
    category: 'Other',
    amount: 600,
    date: '2026-09-26',
    notes: 'Suit jacket dry clean',
    merchant: 'SpinCycle',
  },
  {
    id: 'tx-14',
    type: 'expense',
    description: 'Organic Produce & Dairy',
    category: 'Food',
    amount: 2000,
    date: '2026-09-17',
    notes: 'Artisan sourdough & organic dairy',
    merchant: 'Third Wave Market',
  },
  {
    id: 'tx-15',
    type: 'expense',
    description: 'Gourmet Cafe & Dining',
    category: 'Food',
    amount: 2000,
    date: '2026-09-25',
    notes: 'Weekend brunch & specialty coffee',
    merchant: 'Blue Tokai Cafe',
  },
  {
    id: 'tx-16',
    type: 'expense',
    description: 'Annual Maintenance & Services',
    category: 'Other',
    amount: 5000,
    date: '2026-09-28',
    notes: 'Home appliance warranty & maintenance',
    merchant: 'Urban Company',
  },

  // August 2026 data
  {
    id: 'tx-prev-1',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 47500,
    date: '2026-08-01',
  },
  {
    id: 'tx-prev-2',
    type: 'expense',
    description: 'Monthly Expenses Aggregation',
    category: 'Bills',
    amount: 28300,
    date: '2026-08-15',
  },
  {
    id: 'tx-prev-3',
    type: 'expense',
    description: 'Food & Dining',
    category: 'Food',
    amount: 5400,
    date: '2026-08-20',
  },
  {
    id: 'tx-prev-4',
    type: 'expense',
    description: 'Transport & Commute',
    category: 'Transport',
    amount: 3250,
    date: '2026-08-25',
  },

  // July 2026
  {
    id: 'tx-jul-1',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 47500,
    date: '2026-07-01',
  },
  {
    id: 'tx-jul-2',
    type: 'expense',
    description: 'Expenses',
    category: 'Shopping',
    amount: 22000,
    date: '2026-07-15',
  },

  // June 2026 - matches chart tooltip (₹24,850)
  {
    id: 'tx-jun-1',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 47500,
    date: '2026-06-01',
  },
  {
    id: 'tx-jun-2',
    type: 'expense',
    description: 'Summer Spending',
    category: 'Shopping',
    amount: 24850,
    date: '2026-06-15',
  },

  // May 2026
  {
    id: 'tx-may-1',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 47500,
    date: '2026-05-01',
  },
  {
    id: 'tx-may-2',
    type: 'expense',
    description: 'Expenses',
    category: 'Food',
    amount: 18500,
    date: '2026-05-15',
  },

  // April 2026
  {
    id: 'tx-apr-1',
    type: 'income',
    description: 'Salary',
    category: 'Salary',
    amount: 45000,
    date: '2026-04-01',
  },
  {
    id: 'tx-apr-2',
    type: 'expense',
    description: 'Expenses',
    category: 'Bills',
    amount: 12000,
    date: '2026-04-15',
  },
];
